name: Build Android and iOSon

on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      -name: Install cli
      run: |
        npm install react-native-cli

      - name: Create bundle
        run: |
          react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      
      - name: Clean Release
        run: |
          cd android && ./gradlew clean
      - name: Create build
        run: |
          cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/